spring:
  datasource:
    url: jdbc:mysql://106.15.42.179:3303/practice?useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
