spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice?useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    #本地数据库的密码
    password: 'myxmyx1207'
    driver-class-name: com.mysql.jdbc.Driver

  #文件大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


  #JPA配置
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: none

#logging:
#  config: classpath:logback.xml

springdoc:
  packagesToScan: com.example.webpractice.controller


