spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice?useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root


